// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1OP0e1qMh7_m8Lo4rHth6wmKEWavt9nA',
    appId: '1:36328698467:android:f64b063e00df3d25087e56',
    messagingSenderId: '36328698467',
    projectId: 'todoapp-28df9',
    storageBucket: 'todoapp-28df9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByAfZZxxPVYDcaJj1PlaSxnVdu1h83nFI',
    appId: '1:36328698467:ios:de92a59cea8a136e087e56',
    messagingSenderId: '36328698467',
    projectId: 'todoapp-28df9',
    storageBucket: 'todoapp-28df9.firebasestorage.app',
    androidClientId: '36328698467-iqiogkevl4bqr91b4j4a39hvbc21rnh9.apps.googleusercontent.com',
    iosClientId: '36328698467-vuq595b4vlsh9nd57rfaq3erfm6upd5o.apps.googleusercontent.com',
    iosBundleId: 'com.sy.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsP1aiUc6Tw_WeTBqcQzslHmWO-wODn6I',
    appId: '1:36328698467:web:54b8a3a1dd673213087e56',
    messagingSenderId: '36328698467',
    projectId: 'todoapp-28df9',
    authDomain: 'todoapp-28df9.firebaseapp.com',
    storageBucket: 'todoapp-28df9.firebasestorage.app',
    measurementId: 'G-6HB95XP6H5',
  );

}